
services:
  spring-app:
    build:
      context: ../PROJETO02
    container_name: spring-app
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://10.100.122.170/newwmaildb
      SPRING_DATASOURCE_USERNAME: springboot
      SPRING_DATASOURCE_PASSWORD: sua_senha
    networks:
      - app-network

  php-app:
    build:
      context: ./php-app
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - ./php-app:/var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
